org: thaer899
app: myresume-utils
service: myresume-utils

frameworkVersion: "3"

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.9
  stage: prod
  region: eu-west-1

functions:
  utils:
    handler: wsgi_handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-wsgi
  - serverless-python-requirements
