FROM python:3.9-slim

# Install dependencies
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  wget \
  unzip \
  xvfb \
  libxi6 \
  libgconf-2-4 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Set up Chrome WebDriver
RUN wget https://chromedriver.storage.googleapis.com/95.0.4638.17/chromedriver_linux64.zip && \
  unzip chromedriver_linux64.zip && \
  mv chromedriver /usr/local/bin && \
  rm chromedriver_linux64.zip

# Set up the working directory
WORKDIR /app

# Copy the Python scripts or Jupyter notebooks into the Docker image
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run your script
CMD ["python", "./multi_task.py"]
