apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.appName}}-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{.Values.appName}}"
  template:
    metadata:
      labels:
        app: "{{.Values.appName}}"
    spec:
      containers:
        - name: "{{.Values.appName}}-container"
          image: "{{.Values.registry}}/{{.Values.projectName}}/{{.Values.appName}}:latest"
          ports:
            - containerPort: 4000
          resources:
            limits:
              nvidia.com/gpu: 1
          env:
            - name: FIREBASE_CREDENTIALS_PATH
              valueFrom:
                secretKeyRef:
                  name: "{{.Values.appName}}-secret"
                  key: FIREBASE_CREDENTIALS_PATH
          volumeMounts:
            - name: "{{ .Values.appName }}-pv"
              mountPath: /app
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
      volumes:
        - name: "{{ .Values.appName }}-pv"
          persistentVolumeClaim:
            claimName: "{{ .Values.appName }}-pvc"
