apiVersion: v1
kind: Secret
metadata:
  name: "{{.Values.appName}}-secret"
  annotations:
    meta.helm.sh/release-name: myresume-express
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  FIREBASE_CREDENTIALS_PATH: "{{.Values.FIREBASE_CREDENTIALS_PATH}}"
