# Use the slim version of Python 3.9
FROM python:3.9-slim

# Install dependencies
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  wget \
  unzip \
  xvfb \
  libxi6 \
  libgconf-2-4 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Set up the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 33000 available to the world outside this container
EXPOSE 33000

# Run uvicorn when the container launches
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "33000", "--reload"]
