openapi: 3.0.0
info:
  title: myresume-express-api
  version: 1.0.0
paths:
  /:
    get:
      summary: Retrieve LogBook profile details
      responses:
        "200":
          description: Successful operation
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /quote:
    post:
      summary: Generate a personalized quote based on a LogBook profile
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /message:
    post:
      summary: Respond to a user's message using the LogBook profile
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipientMessage:
                  type: string
      responses:
        "200":
          description: Successful operation
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /skill:
    post:
      summary: Retrieve information about a specified skill
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipientMessage:
                  type: string
      responses:
        "200":
          description: Successful operation
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /blog:
    post:
      summary: Generate a blog post using LogBook profile
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipientMessage:
                  type: string
      responses:
        "200":
          description: Successful operation
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /openai:
    post:
      summary: Execute a specific OpenAI operation
      parameters:
        - name: email
          in: query
          required: false
          schema:
            type: string
        - name: templateType
          in: query
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Successful operation
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
components:
  securitySchemes:
    Authorization:
      type: apiKey
      in: header
      name: apiKey
security:
  - Authorization: []
