apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.appName}}-service"
spec:
  selector:
    app: "{{.Values.appName}}"
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 33000
