apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.appName }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.appName }}"
    spec:
      containers:
        - name: "{{ .Values.appName }}-container"
          image: "{{ .Values.registry }}/{{ .Values.projectName }}/{{ .Values.appName }}:latest"
          args:
            - "--project-id={{ .Values.projectName }}"
            - "--cluster={{ .Values.clusterName }}"
            - "--location={{ .Values.location }}"
          ports:
            - containerPort: "{{ .Values.containerPort }}"
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.appName }}-secret"
                  key: OPENAI_API_KEY
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.appName }}-secret"
                  key: API_KEY
          livenessProbe:
            httpGet:
              path: /
              port: "{{ .Values.containerPort }}"
            initialDelaySeconds: 60
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: "{{ .Values.containerPort }}"
            initialDelaySeconds: 60
            timeoutSeconds: 10
