name: my-resume-ng
run-name: my-resume-ng-${{ (github.event.inputs.env != 'nah') && github.event.inputs.env || 'no-deploy' }}-${{ github.run_number }}${{ (github.event.inputs.test == 'true') && '-test' || '' }}

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: environment
        required: false
        default: no
        options:
          - nah
          - dev
          - prod
      test:
        type: boolean
        description: Test
        required: false
        default: false

jobs:

  dev:
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.env == 'dev')
    runs-on: ubuntu-latest
    name: Build Job
    steps:
     - uses: actions/checkout@v3
     - name: Use Node.js 18.x
       uses: actions/setup-node@v3
       with:
         node-version: 18.x
         cache: 'npm'
     - run: npm ci
     - run: npm run build --configuration=development --if-present

  test:
   if: (always() && github.event_name == 'workflow_dispatch' && github.event.inputs.test == 'true')
   needs: dev
   runs-on: ubuntu-latest
   name: Test Job
   steps:
     - uses: actions/checkout@v3
     - name: Use Node.js 18.x
       uses: actions/setup-node@v3
       with:
         node-version: 18.x
         cache: 'npm'
     - name: Install dependencies
       run: npm ci
     - name: Install Playwright Browsers
       run: npx playwright install --with-deps
     - name: Run Playwright tests
       run: npx playwright test
     - uses: actions/upload-artifact@v3
       if: always()
       with:
         name: playwright-report
         path: playwright-report/
         retention-days: 30

  prod:
    needs: test
    if: (always() && github.event_name == 'workflow_dispatch' && github.event.inputs.env == 'prod')
    runs-on: ubuntu-latest
    name: Deploy Job
    steps:
    - uses: actions/checkout@v3
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_WAVE_04CA68203 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: 'upload'
        app_location: '/'
        api_location: 'api'
        app_artifact_location: 'dist/angular-basic/browser'
