name: myresume-express
run-name: myresume-express-${{github.event.inputs.job}}:${{ github.run_number }}

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      job:
        type: choice
        description: 'Task to run'
        required: false
        options:
          - build
          - deploy

jobs:
  build:
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.job == 'build' )
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: eu.gcr.io/thaersaidi-da79c/myresume-express:${{ github.run_number }}

    permissions:
      contents: 'read'
      id-token: 'write'      

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to Google Container Registry
        uses: docker/login-action@v1 
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCP_THAERSAIDI_SA }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./myresume-express
          push: true
          tags: ${{ env.IMAGE_TAG }}

  deploy:
    if: (always() && github.event_name == 'workflow_dispatch' && github.event.inputs.job == 'deploy' ) || ( github.event_name == 'push' )
    needs: build
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: myresume-ai
      IMAGE_TAG: eu.gcr.io/thaersaidi-da79c/myresume-express:latest
      RELEASE_NAME: myresume-express
      CHART_PATH: ./utils/helm/myresume-ai/apps/myresume-express
      PROJECT_ID: thaersaidi-da79c
      CLUSTER_REGION: europe-west1
      ACCOUNT: 'thaersaidi-sa@thaersaidi-da79c.iam.gserviceaccount.com'
      WORKLOAD_IDENTITY_PROVIDER: 'iam.googleapis.com/projects/250500941343/locations/global/workloadIdentityPools/github-actions/subject/SUBJECT_ATTRIBUTE_VALUE'

    permissions:
      contents: 'read'
      id-token: 'write'      

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Auth to Google Cloud SDK'
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.ACCOUNT }}
  
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
          
      - name: Authenticate to the cluster
        run: |
          gcloud auth list
          ls
          sudo apt-get install jq
          KEY_FILE=$(ls gha-creds-*.json | head -n 1)
          echo "Using key file $KEY_FILE"
          cat $KEY_FILE
          if jq . "$KEY_FILE" >/dev/null 2>&1; then
              echo "JSON is valid"
          else
              echo "Invalid JSON"
          fi
          gcloud auth activate-service-account --key-file=$KEY_FILE 
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --region ${{ env.CLUSTER_REGION }} --project ${{ env.PROJECT_ID }} || gcloud feedback --verbosity=debug
      
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.5.2'
    
      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install ${{ env.RELEASE_NAME }} ${{ env.CHART_PATH }} --set image.tag=${{ env.IMAGE_TAG }}
