name: myresume-ai
run-name: myresume-ai-${{ github.run_number }}-${{ github.event.inputs.app }}:${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      app:
        type: choice
        description: 'Application'
        required: true
        options:
          - myresume-express
          - other-app
      job:
        type: choice
        description: 'Job'
        required: true
        options:
          - deploy
      common:
        type: boolean
        description: 'Common'
        required: true
        default: false

jobs:
  deploy:
    if: github.event.inputs.job == 'deploy'
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: myresume-ai
      PROJECT_ID: thaersaidi-da79c
      APP_NAME: ${{ github.event.inputs.app }}
      IMAGE_REGISTRY: eu.gcr.io
      IMAGE_TAG: eu.gcr.io/thaersaidi-da79c/myresume-express:${{ github.run_number }}
      APP_CHART_PATH: ./utils/helm/myresume-ai/apps/${{ github.event.inputs.app }}
      COMMON_CHART_PATH: ./utils/helm/myresume-ai/common
      CLUSTER_REGION: europe-west1
      CLOUDSDK_AUTH_ACCESS_TOKEN: ${{ secrets.GCP_THAERSAIDI_SA }}
      WORKLOAD_IDENTITY_PROVIDER: 'projects/250500941343/locations/global/workloadIdentityPools/github-actions/subject/SUBJECT_ATTRIBUTE_VALUE'
      SERVICE_ACCOUNT: 'automation@thaersaidi-da79c.iam.gserviceaccount.com'

    permissions:
      contents: 'read'
      id-token: 'write'      

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GCP_THAERSAIDI_SA }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./myresume-express
          push: true
          tags: ${{ env.IMAGE_TAG }}

      - name: 'Auth to Google Cloud SDK'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
  
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.5.2'

      - name: Deploy to Kubernetes
        run: |
          echo ${{env.CLOUDSDK_AUTH_ACCESS_TOKEN}} > creds.json
          gcloud auth login --cred-file=./creds.json
          gcloud config set account ${{ env.ACCOUNT }}
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --region ${{ env.CLUSTER_REGION }} --project ${{ env.PROJECT_ID }}
          helm upgrade --install ${{ env.APP_NAME }}-${{ github.run_number }} ${{ env.APP_CHART_PATH }}
          rm creds.json

      - name: Deploy Common Chart to Kubernetes
        if: github.event.inputs.common == 'true'
        run: |
          echo ${{env.CLOUDSDK_AUTH_ACCESS_TOKEN}} > creds.json
          gcloud auth login --cred-file=./creds.json
          gcloud config set account ${{ env.ACCOUNT }}
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --region ${{ env.CLUSTER_REGION }} --project ${{ env.PROJECT_ID }}
          helm upgrade --install ${{ env.APP_NAME }}-${{ github.run_number }} ${{ env.COMMON_CHART_PATH }}
          rm creds.json