name: myresume-express
run-name: myresume-express:${{ github.run_number }}

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      job:
        type: choice
        description: 'Task to run'
        required: true
        default: 'build'
        options:
          - build
          - deploy

jobs:
  build:
    if: github.event.inputs.job == 'build'
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: eu.gcr.io/thaersaidi-da79c/myresume-express:${{ github.run_number }}

    permissions:
      contents: 'read'
      id-token: 'write'      

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to Google Container Registry
        uses: docker/login-action@v1 
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCP_THAERSAIDI_SA }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./myresume-express
          push: true
          tags: ${{ env.IMAGE_TAG }}

  deploy:
    if: (always() && github.event.inputs.job == 'deploy')
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: myresume-ai
      IMAGE_TAG: eu.gcr.io/thaersaidi-da79c/myresume-express:latest
      RELEASE_NAME: myresume-express
      CHART_PATH: ./utils/helm/myresume-ai/apps/myresume-express
      PROJECT_ID: thaersaidi-da79c
      CLUSTER_REGION: europe-west1
      ACCOUNT: thaersaidi-da79c@appspot.gserviceaccount.com
      CLOUDSDK_AUTH_ACCESS_TOKEN: ${{ secrets.GCP_THAERSAIDI_SA }}

    permissions:
      contents: 'read'
      id-token: 'write'      

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Auth to Google Cloud SDK'
        uses: 'google-github-actions/auth@v1'
        id: auth
        with:
          workload_identity_provider: 'projects/250500941343/locations/global/workloadIdentityPools/github-actions/subject/SUBJECT_ATTRIBUTE_VALUE'
          service_account: 'automation@thaersaidi-da79c.iam.gserviceaccount.com'
  
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
          
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.5.2'

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=/home/runner/work/thaersaidi.net/thaersaidi.net/gha-creds-4e6e388087e85d9c.json" >> $GITHUB_ENV
        
      - name: Authenticate with GCP
        run: gcloud auth activate-service-account --key-file=${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
      
      - name: Authenticate to the cluster
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --region ${{ env.CLUSTER_REGION }} --project ${{ env.PROJECT_ID }}

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install ${{ env.RELEASE_NAME }} ${{ env.CHART_PATH }} --set image.tag=${{ env.IMAGE_TAG }}
