name: myresume-express

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Task to run'
        required: true
        options:
          - test
          - deploy

jobs:
  deploy:
    if: github.event.inputs.job == 'deploy'
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: eu.gcr.io/thaersaidi-da79c/myresume-express:${{ github.run_number }}
      RELEASE_NAME: myresume-express
      CHART_PATH: ./utils/helm/myresume-ai/apps/myresume-express
      PROJECT_ID: thaersaidi-da79c
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to Google Container Registry
        uses: docker/login-action@v1 
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.FIREBASE_SECRET_MYRESUME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          variant: '>= 363.0.0'
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.FIREBASE_SECRET_MYRESUME }}
          export_default_credentials: true

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.5.2'

      - name: Deploy to Kubernetes
        run: |
          gcloud config set compute/zone your-compute-zone
          gcloud container clusters get-credentials your-cluster-name
          helm upgrade --install ${{ env.RELEASE_NAME }} ${{ env.CHART_PATH }} --set image.tag=${{ env.IMAGE_TAG }}
