name: myresume-express
run-name: myresume-express-${{ github.event.inputs.job }}-${{ github.run_number }}
on:
  workflow_dispatch:
    inputs:
      job:
        type: choice
        description: Task to run
        required: true
        options:
          - test
          - deploy

jobs:
  deploy:
    if:  github.event.inputs.job == 'deploy'
    name: Deploy Job
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      API_KEY: ${{ secrets.API_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: cd myresume-express && actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: cd myresume-express && sudo apt install snapd
    - run: cd myresume-express && sudo snap install yq
    - run: cd myresume-express && yq -i '.functions.message.environment.OPENAI_API_KEY =  "${{ env.OPENAI_API_KEY }}"' serverless.yml
    - run: cd myresume-express && yq -i '.functions.message.environment.API_KEY =  "${{ env.API_KEY }}"' server/serverless.yml
    - run: cd myresume-express && npm install -g serverless
    - run: cd myresume-express && serverless config credentials --provider aws --key ${{ secrets.AWS_LAMDA_KEY }} --secret ${{ secrets.AWS_LAMDA_SECRET }}
    - run: cd myresume-express && npm install
    - run: cd myresume-express && serverless deploy
     
