name: myresume-ng
run-name: myresume-ng-${{ github.run_number }}${{ (github.event.inputs.test == 'true') && '-test' || '' }}

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: environment
        required: false
        default: no
        options:
          - net
          - com
      test:
        type: boolean
        description: Test
        required: false
        default: false

jobs:
  test:
   if: (always() && github.event_name == 'workflow_dispatch' && github.event.inputs.test == 'true')
   runs-on: ubuntu-latest
   name: Test Job
   steps:
     - uses: actions/checkout@v3
     - name: Use Node.js 18.x
       uses: actions/setup-node@v3
       with:
         node-version: 18.x
         cache: 'npm'
         cache-dependency-path: myresume-ng/package-lock.json

     - name: Install dependencies
       run: cd myresume-ng && npm ci
     - name: Install Playwright Browsers
       run: cd myresume-ng && npx playwright install --with-deps
     - name: Run Playwright tests
       run: cd myresume-ng && nnpx playwright test
     - uses: actions/upload-artifact@v3
       if: always()
       with:
         name: playwright-report
         path: playwright-report/
         retention-days: 30
  net:
   needs: test
   if: (always() && github.event_name == 'workflow_dispatch' && github.event.inputs.env == 'net')
   runs-on: ubuntu-latest
   name: thaersaidi.net Job
   steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: myresume-express/package-lock.json
    - run: cd myresume-ng && nnpm ci
    - run: cd myresume-ng && nnpm run build --configuration=development --if-present
  com:
    needs: test
    if: (always() && github.event_name == 'workflow_dispatch' && github.event.inputs.env == 'com')
    runs-on: ubuntu-latest
    name: thaersaidi.com Job
    steps:
    - uses: actions/checkout@v3
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_WAVE_04CA68203 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: 'upload'
        app_location: 'myresume-ng/'
        api_location: 'myresume-ng/api'
        app_artifact_location: 'myresume-ng/dist/angular-basic/browser'
