name: site-generator-ng
run-name: site-generator-ng-${{ github.event.inputs.job }}-${{ github.run_number }}
on:
  workflow_dispatch:
    inputs:
      job:
        type: choice
        description: Task to run
        required: true
        options:
          - deploy
jobs:
  deploy:
    if:  github.event.inputs.job == 'deploy'
    name: Deploy Job
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      API_KEY: ${{ secrets.API_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: site-generator-ng/package-lock.json

    - name: Install Firebase Tools
      run: npm install -g firebase-tools
      working-directory: site-generator-ng

    - name: Install Dependencies
      run: npm install
      working-directory: site-generator-ng
      env:
        NODE_OPTIONS: --openssl-legacy-provider

    - name: Build Project
      run: npm run build
      working-directory: site-generator-ng
      env:
        NODE_OPTIONS: --openssl-legacy-provider
    
    - name: Set up Firebase Service Account
      run: echo "${{ secrets.FIREBASE_SECRET_SITE_GENERATOR }}" > ./firebase-service-account.json
      working-directory: site-generator-ng

    - name: Deploy to Firebase
      run: firebase deploy
      working-directory: site-generator-ng
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ./firebase-service-account.json

